controllers_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute

controllers_front:
    resource: ../src/Controller/Front
    name_prefix: front_
    type: attribute

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix: admin_
    prefix: /admin/